export const CONTACT_FORM_UPDATED = 'CONTACT_FORM_UPDATED'
export const CONTACT_FORM_SUBMITTED = 'CONTACT_FORM_SUBMITTED'
export const CONTACT_FORM_POSTED = 'CONTACT_FORM_POSTED'
export const CONTACT_FORM_FAILED = 'CONTACT_FORM_FAILED'