export const STICKY_ICKY_STUCKED = 'STICKY_ICKY_STUCKED'
export const STICKY_ICKY_UNSTUCKED = 'STICKY_ICKY_UNSTUCKED'
export const STICKY_ICKY_ADDED = 'STICKY_ICKY_ADDED'
export const STICKY_ICKY_WIDTH_CHANGE = 'STICKY_ICKY_WIDTH_CHANGE'